# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xczu9eg-ffvb1156-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir A:/Documents/code/VivadoLab/ripple_carry_adder_16bit/ripple_carry_adder_16bit.cache/wt [current_project]
set_property parent.project_path A:/Documents/code/VivadoLab/ripple_carry_adder_16bit/ripple_carry_adder_16bit.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zcu102:part0:3.0 [current_project]
set_property ip_output_repo a:/Documents/code/VivadoLab/ripple_carry_adder_16bit/ripple_carry_adder_16bit.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib A:/Documents/code/VivadoLab/ripple_carry_adder_16bit/ripple_carry_adder_16bit.srcs/sources_1/new/Ripple_Carry_Adder_16bit.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top Ripple_Carry_Adder -part xczu9eg-ffvb1156-2-i


write_checkpoint -force -noxdef Ripple_Carry_Adder.dcp

catch { report_utilization -file Ripple_Carry_Adder_utilization_synth.rpt -pb Ripple_Carry_Adder_utilization_synth.pb }
